services:

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak-container
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
